classes='''All Souls Oxford,
Balliol Oxford,
Christ Church Oxford,
Hertford Oxford,
Jesus Oxford,
Keble Oxford,
Magdalen Oxford,
New Oxford,
Oriel Oxford,
Trinity Oxford,
Radcliffe Camera Oxford,
Cornmarket Oxford,
Bodleian Oxford,
Pitt Rivers Oxford,
Ashmolean Oxford,
Worcester Oxford,
Oxford'''
